language:
  - java

before_install:
# Install Testspace Runner
  - ./testspace_install.sh

script:
  - mvn clean compile
  - mvn cobertura:cobertura -Dcobertura.report.format=xml

# Publish Test Results along with Coverage
  - export PATH="${HOME}/testspace:${PATH}"
# Testspace credentials: "credentials@myorg.testspace.com/myproject/myspace
  - testspace config url ${TESTSPACE_USER_TOKEN}:@${TESTSPACE_URL}
  - testspace publish [Tests]./target/surefire-reports/junitreports/TEST*.xml{src/test/java/com/testspace/java} ./target/site/cobertura/coverage.xml
